spring:
    application:
        name: @project.artifactId@
server:
    servlet:
        context-path: /business-aggregate-admin
    port: @web.port@

zookeeper:
    connect-string: @zookeeper.address@
